---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-perryplex-deluge-config
  namespace: perryplex
  annotations:
spec:
  storageClassName: nfs-kubeconfigs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  namespace: perryplex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
      - name: deluge
        image: linuxserver/deluge:latest
        ports:
        - containerPort: 8112
          protocol: TCP
          name: delugeui
        - containerPort: 6881
          protocol: TCP
          name: delugeintcp
        - containerPort: 6881
          protocol: UDP
          name: delugeinudp
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: 'Australia/Brisbane'
        - name: DELUGE_LOGLEVEL
          value: 'error'
        volumeMounts:
        - name: deluge-config
          mountPath: /config
        - name: deluge-data-downloads
          mountPath: /downloads
      volumes:
      - name: deluge-config
        nfs:
          server: perrynas
          path: /KubeConfigs/deluge
      - name: deluge-data-downloads
        nfs:
          server: perrynas
          path: /Downloads
---
apiVersion: v1
kind: Service
metadata:
  name: deluge
  namespace: perryplex
spec:
  selector:
    app: deluge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8112
      name: delugeui
    - protocol: TCP
      port: 8661
      targetPort: 8661
      name: delugeintcp
    - protocol: UDP
      port: 8661
      targetPort: 8661
      name: delugeinudp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: perryplex-deluge-ingress
  namespace: perryplex
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
    nginx.org/redirect-to-https: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - deluge.perryinc2.net
    secretName: tls-deluge.perryinc2.net-deluge
  rules:
  - host: deluge.perryinc2.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deluge
            port:
              number: 80