---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-perryplex-sabnzbd-config
  namespace: perryplex
  annotations:
spec:
  storageClassName: nfs-kubeconfigs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: perryplex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: linuxserver/sabnzbd:latest
        ports:
        - containerPort: 8989
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: 'Australia/Brisbane'
        volumeMounts:
        - name: sabnzbd-config
          mountPath: /config
        - name: sabnzbd-data-downloads
          mountPath: /downloads
      volumes:
      - name: sabnzbd-config
        persistentVolumeClaim:
          claimName: pvc-nfs-perryplex-sabnzbd-config
      - name: sabnzbd-data-downloads
        persistentVolumeClaim:
          claimName: pvc-smb-perryplex-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: perryplex
spec:
  selector:
    app: sabnzbd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: perryplex-sabnzbd-ingress
  namespace: perryplex
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
    nginx.org/redirect-to-https: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sabnzbd.perryinc2.net
    secretName: tls-sabnzbd.perryinc2.net-sabnzbd
  rules:
  - host: sabnzbd.perryinc2.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sabnzbd
            port:
              number: 80