---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: perryplex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: 'Australia/Brisbane'
        volumeMounts:
        - name: sonarr-config
          mountPath: /config
        - name: sonarr-data-tvshows
          mountPath: /tv
        - name: sonarr-data-tvshows2
          mountPath: /tv2
        - name: sonarr-data-tvshows3
          mountPath: /tv3
        - name: sonarr-data-downloads
          mountPath: /downloads
      volumes:
      - name: sonarr-config
        nfs:
          server: perrynas
          path: /KubeConfigs/sonarr
      - name: sonarr-data-tvshows
        nfs:
          server: perrynas
          path: /Media/TVShows
      - name: sonarr-data-tvshows2
        nfs:
          server: perrynas
          path: /Media/TVShows2
      - name: sonarr-data-tvshows3
        nfs:
          server: perrynas
          path: /PerryData12TB/TVShows3
      - name: sonarr-data-downloads
        nfs:
          server: perrynas
          path: /Downloads
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: perryplex
spec:
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8989
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: perryplex-sonarr-ingress
  namespace: perryplex
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
    nginx.org/redirect-to-https: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sonarr.perryinc2.net
    secretName: tls-sonarr.perryinc2.net-sonarr
  rules:
  - host: sonarr.perryinc2.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 80